[package]
name = "django-deploy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.4.0"
colored = "2.0.0"
sudo = "0.6.0"
fs_extra = "1.2.0"